version: '3.8'

services:
  gateway:
    build:
      context: ../fitnes-gateway
      dockerfile: ../fitnes-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - accounts
      - lessons
    networks:
      - fitnes_network
    environment:
      GATEWAY_ADDRESS: "8080"
      GATEWAY__TIMEOUT: "5s"
      GATEWAY_IDLETIMEOUT: "60s"

      GATEWAY_APPSECRET: "ekxoalmapblaeksraulttoy"

      GATEWAY_CLIENTS_ACCOUNTS_ADDRESS: "accounts:44044"
      GATEWAY_CLIENTS_ACCOUNTS_TIMEOUT: "4s"
      GATEWAY_CLIENTS_ACCOUNTS_RETRIESCOUNT: "10"

      GATEWAY_CLIENTS_LESSONS_ADDRESS: "lessons:4312"
      GATEWAY_CLIENTS_LESSONS_TIMEOUT: "4s"
      GATEWAY_CLIENTS_LESSONS_RETRIESCOUNT: "10"

  accounts:
    build:
      context: ../fitnes-accounts
      dockerfile: ../fitnes-accounts/Dockerfile
    ports:
      - "44044:44044"
    networks:
      - fitnes_network
    environment:
      ACCOUNTS_REPO_HOST: accountsDb # Используйте имя сервиса PostgreSQL
      ACCOUNTS_REPO_PORT: "5432"
      ACCOUNTS_REPO_USER: "postgres"
      ACCOUNTS_REPO_PASSWORD: "postgres"
      ACCOUNTS_REPO_DATABASE: "accounts"
      ACCOUNTS_GRPC_PORT: "44044"
      ACCOUNTS_GRPC_TIMEOUT: "7s"
      ACCOUNTS_SERVICE_TOKENTTL: "1h"

  lessons:
    build:
      context: ../fitnes-lessons
      dockerfile: ../fitnes-lessons/Dockerfile
    ports:
      - "4312:4312"
    networks:
      - fitnes_network
    environment:
      LESSONS_REPO_HOST: lessonsDb # Используйте имя сервиса PostgreSQL
      LESSONS_REPO_PORT: "5432"
      LESSONS_REPO_USER: "postgres"
      LESSONS_REPO_PASSWORD: "postgres"
      LESSONS_REPO_DATABASE: "lessons"
      LESSONS_GRPC_PORT: "4312"
      LESSONS_GRPC_TIMEOUT: "7s"
networks:
  fitnes_network:
    driver: bridge