version: '3.8'

services:
  lessonsDb:
    image: postgres:14.5
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lessons
    volumes:
      - ./schemas/lessons:/docker-entrypoint-initdb.d
    networks:
      - fitnes_network
  accountsDb:
    image: postgres:14.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts
    volumes:
      - ./schemas/accounts:/docker-entrypoint-initdb.d
    networks:
      - fitnes_network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kola2003.ryabof@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - lessonsDb
      - accountsDb
    networks:
      - fitnes_network

networks:
  fitnes_network:
    driver: bridge